version: '3'

tasks:
  default:
    desc: "Показывает доступные задачи."
    cmds:
      - task --list-all

  up:
    desc: "Собрать образы и запустить все сервисы в фоновом режиме."
    cmds:
      - docker-compose up -d --build

  start:
    desc: "Запустить существующие контейнеры (без пересборки)."
    cmds:
      - docker-compose up -d

  stop:
    desc: "Остановить запущенные сервисы."
    cmds:
      - docker-compose stop

  down:
    desc: "Остановить и удалить контейнеры."
    cmds:
      - docker-compose down

  clean:
    desc: "Остановить, удалить контейнеры, сети и тома данных."
    prompt: "Вы уверены? (y/n)"
    cmds:
      - docker-compose down -v

  logs:
    desc: "Показать логи всех сервисов."
    cmds:
      - docker-compose logs

  ps:
    desc: "Показать статус контейнеров."
    cmds:
      - docker-compose ps
  
  swag:
    desc: "Сгенерировать документацию Swagger UI."
    cmds:
      - swag init -g ./backend/cmd/main.go -o ./backend/docs
