{
 "title": "Backend Service Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total Requests (All Time)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(http_requests_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Requests per Second (RPS)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m]))",
     "legendFormat": "Total RPS"
    }
   ]
  },
  {
   "title": "Error Rate (5xx)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[5m])) / sum(rate(http_requests_total[5m])) * 100",
     "legendFormat": "5xx Error Rate (%)"
    }
   ]
  },
  {
   "title": "Request Latency (99th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_requests_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "P99 Latency"
    }
   ]
  },
  {
   "title": "Error Count by Endpoint (5xx)",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{status=~\"5..\"}[5m])) by (path, method)"
    }
   ]
  },
  {
   "title": "RPS by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (path, method)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Backend Gin logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 15, "x": 9, "y": 15 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"backend\"} |= ``"
    }
   ]
  },
  {
   "title": "Latency by Endpoint (P95)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_requests_latency_seconds_bucket[5m])) by (le, path, method))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  }
 ]
}