# Серверные настройки
port: ":8080"

# Настройки подключения к PostgreSQL
postgres:
  user:     "postgres"
  password: "290605"
  database: "bloomify"
  # для docker - "db" | для локального запуска - "localhost"
  host:     "db" 
  # host:     "localhost"
  port:     "5432"
  sslmode:  "disable"
