name: Go CI/CD

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install golint
        run: |
          go install golang.org/x/lint/golint@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH
      - name: Check code style
        run: golint ./...

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        run: docker build -t bloomify-app .
      - name: Run Docker container
        run: docker run -p 8080:8080 bloomify-app