name: Go

on:
  push:
    branches:
    - "**"
  pull_request:
    branches:
    - "**"

jobs:

  codestyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install golint
      run: |
        go install golang.org/x/lint/golint@latest
        echo "$HOME/go/bin" >> $GITHUB_PATH
    - name: codestyle
      run: golint .

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: go build -v ./...