name: Go CI/CD

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20' # Установите нужную версию Go
      - name: Install golint
        run: |
          go install golang.org/x/lint/golint@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH
      - name: Install swag
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH
      - name: Run lint
        run: make lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22' # Установите нужную версию Go
      - name: Run format
        run: make fmt

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22' # Установите нужную версию Go
      - name: Install swag
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Run build and run container
        run: make run