name: Go CI/CD

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Install gotestsum
        run: |
          go install gotest.tools/gotestsum@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH
      - name: Run test
        run: make test

  codestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Install golint
        run: |
          go install golang.org/x/lint/golint@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH
      - name: Run lint
        run: make lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Run format
        run: make fmt
        